doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        driver: '%env(DB_DRIVER)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        dbname: '%env(DB_DATABASE)%'
        user: '%env(DB_USERNAME)%'
        password: '%env(DB_PASSWORD)%'
        server_version: '%env(DB_SERVER_VERSION)%'
        charset: 'utf8'

        schema_filter: '~^(?!messenger_messages)~'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        #entity_managers:
        #    default:
        dql:
            string_functions:
                JSONB_EXIST: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonbExists
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
