flysystem:
    storages:
        s3.storage:
            adapter: 'aws'
            options:
                client: 'aws_client_service'
                # Bucket must be set as public. Variants: via UI (* => Read-Only), via mc (cli), via php client.
                bucket: 'tests'
                options:
                    ACL: 'public-read'