framework:
    messenger:
        failure_transport: failed

        transports:
            emails:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 3000
                    multiplier: 1
                    max_delay: 0

            failed:
                dsn: 'doctrine://default?queue_name=failed'

            sync: 'sync://'

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync
