security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        registration:
            pattern: account.register
            anonymous: true

        verification:
            pattern: account.verify
            anonymous: true

        login:
            pattern: account.login
            stateless: true
            anonymous: true
            json_login:
                check_path: account.login
                #success_handler: lexik_jwt_authentication.handler.authentication_success
                success_handler: App\Security\Authentication\AuthenticationSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_MODERATOR

    access_control:
        # IsGranted в контроллере не поможет, так как ^/api первей выполняется. Только если его убирать.
        - { path: ^/api/v1/account/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/account/verify, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/account/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
