framework:
    # If set default lang to ru, then validation messages are in ru lang, that is wrong.
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - ru
