framework:
    workflows:
        test_publishing:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentStatus'
            supports:
                - App\Entity\Test
            initial_marking: new
            places:
                - new
                - reviewed
                - on_correction
                - approved
            transitions:
                to_review:
                    from: [new, on_correction]
                    to:   reviewed
                approve:
                    guard: "is_granted('ROLE_MODERATOR')"
                    from: reviewed
                    to:   approved
                reject:
                    guard: "is_granted('ROLE_MODERATOR')"
                    from: reviewed
                    to:   on_correction
                back_to_correction:
                    from: reviewed
                    to:   on_correction